name: test-pipeline2

on:
  pull_request_target:
    branches: [ master, main ]
    types:
      - opened
      - synchronize
      - reopened

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo "hello likun2"
