name: test-pipeline-base

on:
  pull_request:
    branches: [ master, main ]
    types:
      - opened
      - synchronize
      - reopened

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo "hello likun base."
